# This file was generated by GoReleaser. DO NOT EDIT.
cask "ovhcloud-cli" do
  version "0.15.0"

  on_macos do
    on_arm do
      sha256 "26b78ca0045dd21db040b2991d8a301bafcb898454ea80b5285a04e184132142"
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5aadbdc9f9eae915fdb13e189fa8e5b492b302418c8b9ef3b57d720128fbbee8"
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5c2beb56e6d83a4b426565a1557791ef759316abcc4effb38dd627c90aeb80e0"
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1109d157dcf677bf3a7616e4b27b4fe3b5cc984e1cc82987592016541a6c88ed"
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Linux_x86_64.tar.gz"
    end
  end

  name "ovhcloud-cli"
  desc "OVHcloud CLI - Command line interface for OVHcloud."
  homepage "https://github.com/ovh/ovhcloud-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ovhcloud"

  # No zap stanza required

  caveats <<~EOS
    See https://github.com/ovh/ovhcloud-cli for usage.
  EOS
end
