# This file was generated by GoReleaser. DO NOT EDIT.
cask "ovhcloud-cli" do
  name "ovhcloud-cli"
  desc "OVHcloud CLI - Command line interface for OVHcloud."
  homepage "https://github.com/ovh/ovhcloud-cli"
  version "0.8.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ovhcloud"

  on_macos do
    on_intel do
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Darwin_x86_64.tar.gz"
      sha256 "eb6c36c56e5e34393fc93bcada8689a20444a4e022d67ca7772fe613e67bd08b"
    end
    on_arm do
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Darwin_arm64.tar.gz"
      sha256 "8dc92ab65b4d08e1882d8f72c32821b590977d676946afc5a9d111649569f7c9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Linux_x86_64.tar.gz"
      sha256 "5ed5c0e37218e3a6aa3d68f84ea35d5909fd58adaa915b5e3aae8b3338c0898d"
    end
    on_arm do
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Linux_arm64.tar.gz"
      sha256 "55978fb0a9660c05a0b82db93a546b746c56e1f2f258cf693e23f31d37586621"
    end
  end

  caveats do
    "See https://github.com/ovh/ovhcloud-cli for usage."
  end

  # No zap stanza required
end
