# This file was generated by GoReleaser. DO NOT EDIT.
cask "ovhcloud" do
  name "ovhcloud"
  desc "OVHcloud CLI - Command line interface for OVHcloud."
  homepage "https://github.com/ovh/ovhcloud-cli"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ovhcloud"

  on_macos do
    on_intel do
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Darwin_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "4a30025eb02be5d7525abffc0263d72ac18c64755f0081df7eca918dd5dbdc35"
    end
    on_arm do
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "dc66c24ec99dbaec42e1c960b6924f7b8394cd31bee1df02d8f9beff3648ed7d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Linux_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "a2a7cefd22476e8ddde3bc0acd9830da07b05d49e226a1d565eba23ba7ef4741"
    end
    on_arm do
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "14454e460608292ae35453bf4a0fd880d12adc5a585b0e057b32f33264da4014"
    end
  end

  caveats do
    "See https://github.com/ovh/ovhcloud-cli for usage."
  end

  # No zap stanza required
end
