# This file was generated by GoReleaser. DO NOT EDIT.
cask "ovhcloud" do
  name "ovhcloud"
  desc "OVHcloud CLI - Command line interface for OVHcloud."
  homepage "https://github.com/ovh/ovhcloud-cli"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ovhcloud"

  on_macos do
    on_intel do
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Darwin_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "6d4ec88b7b807bdb9b37b29a552d7c4c341fc28c9420dacb03804d5ca6a3ce6f"
    end
    on_arm do
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "73938ea0ca5297c6e61514b37775a0ba328f7187ac798f7a97af02c285fb1c9a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Linux_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "96ad867931e29cb5cda19e6ffe5eb79f22d7372c0a0762f877c806c68b6dde46"
    end
    on_arm do
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "0af6980de250d1a66f333fbdc7a1a41f10148aa4110bca249dd0304376f496c4"
    end
  end

  caveats do
    "See https://github.com/ovh/ovhcloud-cli for usage."
  end

  # No zap stanza required
end
