# This file was generated by GoReleaser. DO NOT EDIT.
cask "ovhcloud-cli" do
  name "ovhcloud-cli"
  desc "OVHcloud CLI - Command line interface for OVHcloud."
  homepage "https://github.com/ovh/ovhcloud-cli"
  version "0.8.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ovhcloud"

  on_macos do
    on_intel do
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Darwin_x86_64.tar.gz"
      sha256 "bce031995bcdce40b3fd8d38f5160bfcc182616fb3f8721613f6e5cd36f8f3eb"
    end
    on_arm do
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Darwin_arm64.tar.gz"
      sha256 "00ec5e33eef11c2fe8cf2198ab86055b454afd9cc15e6fd3deaed48d176ae3ee"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Linux_x86_64.tar.gz"
      sha256 "64151a785e06fb44903270f75dd9ac96729877f7410e89c782a2270fc64875a8"
    end
    on_arm do
      url "https://github.com/ovh/ovhcloud-cli/releases/download/v#{version}/ovhcloud-cli_Linux_arm64.tar.gz"
      sha256 "16a9dceb01289c328b1c0fc9b857894286ecd84753619b7c0b9915711cf6cbc4"
    end
  end

  caveats do
    "See https://github.com/ovh/ovhcloud-cli for usage."
  end

  # No zap stanza required
end
